2024-12-31 14:14:27,066 [INFO] PID file for 'polaris' created with PID: 22684
2024-12-31 14:14:27,066 [INFO] PID file for 'polaris' created with PID: 22684
2024-12-31 14:14:27,066 [INFO] PID file for 'polaris' created with PID: 22684
2024-12-31 14:14:27,066 [INFO] PID file for 'polaris' created with PID: 22684
2024-12-31 14:14:27,066 [INFO] Started polaris with PID: 22684
2024-12-31 14:14:27,066 [INFO] Started polaris with PID: 22684
2024-12-31 14:14:27,066 [INFO] Started polaris with PID: 22684
2024-12-31 14:14:27,066 [INFO] Started polaris with PID: 22684
2024-12-31 14:14:27,097 [INFO] PID file for 'compute_subnet' created with PID: 19432
2024-12-31 14:14:27,097 [INFO] PID file for 'compute_subnet' created with PID: 19432
2024-12-31 14:14:27,097 [INFO] PID file for 'compute_subnet' created with PID: 19432
2024-12-31 14:14:27,097 [INFO] PID file for 'compute_subnet' created with PID: 19432
2024-12-31 14:14:27,098 [INFO] Started compute_subnet with PID: 19432
2024-12-31 14:14:27,098 [INFO] Started compute_subnet with PID: 19432
2024-12-31 14:14:27,098 [INFO] Started compute_subnet with PID: 19432
2024-12-31 14:14:27,098 [INFO] Started compute_subnet with PID: 19432
2024-12-31 14:14:28,240 [WARNING] Restarting script with administrative privileges...
2024-12-31 14:14:28,362 [INFO] Script relaunched with administrative privileges.
2024-12-31 14:14:28,362 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 14:14:28,895 [INFO] PID file created with PID: 23656
2024-12-31 14:14:29,101 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 14:14:31,869 [INFO] SSH server configured successfully.
2024-12-31 14:14:31,932 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 14:14:41,432 [INFO] Starting ngrok tunnel...
2024-12-31 14:17:18,685 [ERROR] Failed to stop polaris: (pid=23656)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=23656)
2024-12-31 14:17:18,685 [ERROR] Failed to stop polaris: (pid=23656)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=23656)
2024-12-31 14:17:18,685 [ERROR] Failed to stop polaris: (pid=23656)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=23656)
2024-12-31 14:17:18,685 [ERROR] Failed to stop polaris: (pid=23656)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=23656)
2024-12-31 14:17:18,718 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:17:18,718 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:17:18,718 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:17:18,718 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:18:02,238 [INFO] PID file for 'polaris' created with PID: 28604
2024-12-31 14:18:02,238 [INFO] PID file for 'polaris' created with PID: 28604
2024-12-31 14:18:02,238 [INFO] PID file for 'polaris' created with PID: 28604
2024-12-31 14:18:02,238 [INFO] PID file for 'polaris' created with PID: 28604
2024-12-31 14:18:02,238 [INFO] Started polaris with PID: 28604
2024-12-31 14:18:02,238 [INFO] Started polaris with PID: 28604
2024-12-31 14:18:02,238 [INFO] Started polaris with PID: 28604
2024-12-31 14:18:02,238 [INFO] Started polaris with PID: 28604
2024-12-31 14:18:02,256 [INFO] PID file for 'compute_subnet' created with PID: 3664
2024-12-31 14:18:02,256 [INFO] PID file for 'compute_subnet' created with PID: 3664
2024-12-31 14:18:02,256 [INFO] PID file for 'compute_subnet' created with PID: 3664
2024-12-31 14:18:02,256 [INFO] PID file for 'compute_subnet' created with PID: 3664
2024-12-31 14:18:02,257 [INFO] Started compute_subnet with PID: 3664
2024-12-31 14:18:02,257 [INFO] Started compute_subnet with PID: 3664
2024-12-31 14:18:02,257 [INFO] Started compute_subnet with PID: 3664
2024-12-31 14:18:02,257 [INFO] Started compute_subnet with PID: 3664
2024-12-31 14:18:03,484 [WARNING] Restarting script with administrative privileges...
2024-12-31 14:18:03,637 [INFO] Script relaunched with administrative privileges.
2024-12-31 14:18:03,638 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 14:18:04,266 [INFO] PID file created with PID: 21648
2024-12-31 14:18:04,431 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 14:18:06,601 [INFO] SSH server configured successfully.
2024-12-31 14:18:06,666 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 14:18:16,097 [INFO] Starting ngrok tunnel...
2024-12-31 14:18:24,180 [WARNING] Failed to synchronize network information
2024-12-31 14:18:24,180 [INFO] 
==================================================
2024-12-31 14:18:24,180 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 14:18:24,180 [INFO] SSH Command: ssh HP@4.tcp.eu.ngrok.io -p 19575
2024-12-31 14:18:24,180 [INFO] Password: banadda
2024-12-31 14:18:24,180 [INFO] ==================================================

2024-12-31 14:22:17,286 [ERROR] Failed to stop polaris: (pid=21648)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=21648)
2024-12-31 14:22:17,286 [ERROR] Failed to stop polaris: (pid=21648)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=21648)
2024-12-31 14:22:17,286 [ERROR] Failed to stop polaris: (pid=21648)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=21648)
2024-12-31 14:22:17,286 [ERROR] Failed to stop polaris: (pid=21648)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=21648)
2024-12-31 14:22:17,319 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:22:17,319 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:22:17,319 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:22:17,319 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:22:22,145 [INFO] PID file for 'polaris' created with PID: 28284
2024-12-31 14:22:22,145 [INFO] PID file for 'polaris' created with PID: 28284
2024-12-31 14:22:22,145 [INFO] PID file for 'polaris' created with PID: 28284
2024-12-31 14:22:22,145 [INFO] PID file for 'polaris' created with PID: 28284
2024-12-31 14:22:22,145 [INFO] Started polaris with PID: 28284
2024-12-31 14:22:22,145 [INFO] Started polaris with PID: 28284
2024-12-31 14:22:22,145 [INFO] Started polaris with PID: 28284
2024-12-31 14:22:22,145 [INFO] Started polaris with PID: 28284
2024-12-31 14:22:22,179 [INFO] PID file for 'compute_subnet' created with PID: 2312
2024-12-31 14:22:22,179 [INFO] PID file for 'compute_subnet' created with PID: 2312
2024-12-31 14:22:22,179 [INFO] PID file for 'compute_subnet' created with PID: 2312
2024-12-31 14:22:22,179 [INFO] PID file for 'compute_subnet' created with PID: 2312
2024-12-31 14:22:22,181 [INFO] Started compute_subnet with PID: 2312
2024-12-31 14:22:22,181 [INFO] Started compute_subnet with PID: 2312
2024-12-31 14:22:22,181 [INFO] Started compute_subnet with PID: 2312
2024-12-31 14:22:22,181 [INFO] Started compute_subnet with PID: 2312
2024-12-31 14:22:23,177 [WARNING] Restarting script with administrative privileges...
2024-12-31 14:22:23,290 [INFO] Script relaunched with administrative privileges.
2024-12-31 14:22:23,290 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 14:22:23,882 [INFO] PID file created with PID: 16760
2024-12-31 14:22:24,055 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 14:22:26,227 [INFO] SSH server configured successfully.
2024-12-31 14:22:26,279 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 14:22:35,964 [INFO] Starting ngrok tunnel...
2024-12-31 14:22:43,921 [WARNING] Failed to synchronize network information
2024-12-31 14:22:43,921 [INFO] 
==================================================
2024-12-31 14:22:43,921 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 14:22:43,935 [INFO] SSH Command: ssh HP@4.tcp.eu.ngrok.io -p 14868
2024-12-31 14:22:43,935 [INFO] Password: banadda
2024-12-31 14:22:43,935 [INFO] ==================================================

2024-12-31 14:26:38,913 [ERROR] Failed to stop polaris: (pid=16760)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=16760)
2024-12-31 14:26:38,913 [ERROR] Failed to stop polaris: (pid=16760)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=16760)
2024-12-31 14:26:38,913 [ERROR] Failed to stop polaris: (pid=16760)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=16760)
2024-12-31 14:26:38,913 [ERROR] Failed to stop polaris: (pid=16760)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=16760)
2024-12-31 14:26:38,955 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:26:38,955 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:26:38,955 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:26:38,955 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:26:44,961 [INFO] PID file for 'polaris' created with PID: 11472
2024-12-31 14:26:44,961 [INFO] PID file for 'polaris' created with PID: 11472
2024-12-31 14:26:44,961 [INFO] PID file for 'polaris' created with PID: 11472
2024-12-31 14:26:44,961 [INFO] PID file for 'polaris' created with PID: 11472
2024-12-31 14:26:44,961 [INFO] Started polaris with PID: 11472
2024-12-31 14:26:44,961 [INFO] Started polaris with PID: 11472
2024-12-31 14:26:44,961 [INFO] Started polaris with PID: 11472
2024-12-31 14:26:44,961 [INFO] Started polaris with PID: 11472
2024-12-31 14:26:44,979 [INFO] PID file for 'compute_subnet' created with PID: 27748
2024-12-31 14:26:44,979 [INFO] PID file for 'compute_subnet' created with PID: 27748
2024-12-31 14:26:44,979 [INFO] PID file for 'compute_subnet' created with PID: 27748
2024-12-31 14:26:44,979 [INFO] PID file for 'compute_subnet' created with PID: 27748
2024-12-31 14:26:44,981 [INFO] Started compute_subnet with PID: 27748
2024-12-31 14:26:44,981 [INFO] Started compute_subnet with PID: 27748
2024-12-31 14:26:44,981 [INFO] Started compute_subnet with PID: 27748
2024-12-31 14:26:44,981 [INFO] Started compute_subnet with PID: 27748
2024-12-31 14:26:46,212 [WARNING] Restarting script with administrative privileges...
2024-12-31 14:26:46,379 [INFO] Script relaunched with administrative privileges.
2024-12-31 14:26:46,379 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 14:26:47,011 [INFO] PID file created with PID: 17440
2024-12-31 14:26:47,209 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 14:26:49,539 [INFO] SSH server configured successfully.
2024-12-31 14:26:49,609 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 14:27:01,866 [INFO] Starting ngrok tunnel...
2024-12-31 14:27:11,344 [WARNING] Failed to synchronize network information
2024-12-31 14:27:11,344 [INFO] 
==================================================
2024-12-31 14:27:11,344 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 14:27:11,344 [INFO] SSH Command: ssh://HP@0.tcp.in.ngrok.io:14697
2024-12-31 14:27:11,344 [INFO] Password: banadda
2024-12-31 14:27:11,360 [INFO] ==================================================

2024-12-31 14:29:24,017 [ERROR] Failed to stop polaris: (pid=17440)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=17440)
2024-12-31 14:29:24,017 [ERROR] Failed to stop polaris: (pid=17440)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=17440)
2024-12-31 14:29:24,017 [ERROR] Failed to stop polaris: (pid=17440)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=17440)
2024-12-31 14:29:24,017 [ERROR] Failed to stop polaris: (pid=17440)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=17440)
2024-12-31 14:29:24,046 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:29:24,046 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:29:24,046 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:29:24,046 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 14:29:31,021 [INFO] PID file for 'polaris' created with PID: 8244
2024-12-31 14:29:31,021 [INFO] PID file for 'polaris' created with PID: 8244
2024-12-31 14:29:31,021 [INFO] PID file for 'polaris' created with PID: 8244
2024-12-31 14:29:31,021 [INFO] PID file for 'polaris' created with PID: 8244
2024-12-31 14:29:31,021 [INFO] Started polaris with PID: 8244
2024-12-31 14:29:31,021 [INFO] Started polaris with PID: 8244
2024-12-31 14:29:31,021 [INFO] Started polaris with PID: 8244
2024-12-31 14:29:31,021 [INFO] Started polaris with PID: 8244
2024-12-31 14:29:31,037 [INFO] PID file for 'compute_subnet' created with PID: 2032
2024-12-31 14:29:31,037 [INFO] PID file for 'compute_subnet' created with PID: 2032
2024-12-31 14:29:31,037 [INFO] PID file for 'compute_subnet' created with PID: 2032
2024-12-31 14:29:31,037 [INFO] PID file for 'compute_subnet' created with PID: 2032
2024-12-31 14:29:31,037 [INFO] Started compute_subnet with PID: 2032
2024-12-31 14:29:31,037 [INFO] Started compute_subnet with PID: 2032
2024-12-31 14:29:31,037 [INFO] Started compute_subnet with PID: 2032
2024-12-31 14:29:31,037 [INFO] Started compute_subnet with PID: 2032
2024-12-31 14:29:32,022 [WARNING] Restarting script with administrative privileges...
2024-12-31 14:29:32,143 [INFO] Script relaunched with administrative privileges.
2024-12-31 14:29:32,143 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 14:29:32,687 [INFO] PID file created with PID: 24684
2024-12-31 14:29:32,905 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 14:29:35,060 [INFO] SSH server configured successfully.
2024-12-31 14:29:35,123 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 14:29:44,584 [INFO] Starting ngrok tunnel...
2024-12-31 14:29:52,606 [WARNING] Failed to synchronize network information
2024-12-31 14:29:52,606 [INFO] 
==================================================
2024-12-31 14:29:52,606 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 14:29:52,606 [INFO] SSH Command: ssh://HP@4.tcp.eu.ngrok.io:18240
2024-12-31 14:29:52,606 [INFO] Password: banadda
2024-12-31 14:29:52,606 [INFO] ==================================================

2024-12-31 15:01:06,962 [ERROR] Failed to stop polaris: (pid=24684)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=24684)
2024-12-31 15:01:06,962 [ERROR] Failed to stop polaris: (pid=24684)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=24684)
2024-12-31 15:01:06,962 [ERROR] Failed to stop polaris: (pid=24684)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=24684)
2024-12-31 15:01:06,962 [ERROR] Failed to stop polaris: (pid=24684)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=24684)
2024-12-31 15:01:06,999 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:01:06,999 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:01:06,999 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:01:06,999 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:01:10,884 [INFO] PID file for 'polaris' created with PID: 26600
2024-12-31 15:01:10,884 [INFO] PID file for 'polaris' created with PID: 26600
2024-12-31 15:01:10,884 [INFO] PID file for 'polaris' created with PID: 26600
2024-12-31 15:01:10,884 [INFO] PID file for 'polaris' created with PID: 26600
2024-12-31 15:01:10,897 [INFO] Started polaris with PID: 26600
2024-12-31 15:01:10,897 [INFO] Started polaris with PID: 26600
2024-12-31 15:01:10,897 [INFO] Started polaris with PID: 26600
2024-12-31 15:01:10,897 [INFO] Started polaris with PID: 26600
2024-12-31 15:01:10,901 [INFO] PID file for 'compute_subnet' created with PID: 25136
2024-12-31 15:01:10,901 [INFO] PID file for 'compute_subnet' created with PID: 25136
2024-12-31 15:01:10,901 [INFO] PID file for 'compute_subnet' created with PID: 25136
2024-12-31 15:01:10,901 [INFO] PID file for 'compute_subnet' created with PID: 25136
2024-12-31 15:01:10,901 [INFO] Started compute_subnet with PID: 25136
2024-12-31 15:01:10,901 [INFO] Started compute_subnet with PID: 25136
2024-12-31 15:01:10,901 [INFO] Started compute_subnet with PID: 25136
2024-12-31 15:01:10,901 [INFO] Started compute_subnet with PID: 25136
2024-12-31 15:01:11,989 [WARNING] Restarting script with administrative privileges...
2024-12-31 15:01:12,172 [INFO] Script relaunched with administrative privileges.
2024-12-31 15:01:12,172 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 15:01:12,768 [INFO] PID file created with PID: 10176
2024-12-31 15:01:12,956 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 15:01:15,190 [INFO] SSH server configured successfully.
2024-12-31 15:01:15,247 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 15:01:24,717 [INFO] Starting ngrok tunnel...
2024-12-31 15:01:33,581 [INFO] Network information synchronized successfully
2024-12-31 15:01:34,722 [INFO] 
==================================================
2024-12-31 15:01:34,723 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 15:01:34,723 [INFO] SSH Command: ssh://HP@0.tcp.in.ngrok.io:17093
2024-12-31 15:01:34,723 [INFO] Password: banadda
2024-12-31 15:01:34,723 [INFO] ==================================================

2024-12-31 15:02:40,989 [ERROR] Failed to stop polaris: (pid=10176)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=10176)
2024-12-31 15:02:40,989 [ERROR] Failed to stop polaris: (pid=10176)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=10176)
2024-12-31 15:02:40,989 [ERROR] Failed to stop polaris: (pid=10176)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=10176)
2024-12-31 15:02:40,989 [ERROR] Failed to stop polaris: (pid=10176)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=10176)
2024-12-31 15:02:41,043 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:02:41,043 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:02:41,043 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:02:41,043 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 15:02:44,874 [INFO] PID file for 'polaris' created with PID: 15600
2024-12-31 15:02:44,874 [INFO] PID file for 'polaris' created with PID: 15600
2024-12-31 15:02:44,874 [INFO] PID file for 'polaris' created with PID: 15600
2024-12-31 15:02:44,874 [INFO] PID file for 'polaris' created with PID: 15600
2024-12-31 15:02:44,874 [INFO] Started polaris with PID: 15600
2024-12-31 15:02:44,874 [INFO] Started polaris with PID: 15600
2024-12-31 15:02:44,874 [INFO] Started polaris with PID: 15600
2024-12-31 15:02:44,874 [INFO] Started polaris with PID: 15600
2024-12-31 15:02:44,894 [INFO] PID file for 'compute_subnet' created with PID: 16172
2024-12-31 15:02:44,894 [INFO] PID file for 'compute_subnet' created with PID: 16172
2024-12-31 15:02:44,894 [INFO] PID file for 'compute_subnet' created with PID: 16172
2024-12-31 15:02:44,894 [INFO] PID file for 'compute_subnet' created with PID: 16172
2024-12-31 15:02:44,894 [INFO] Started compute_subnet with PID: 16172
2024-12-31 15:02:44,894 [INFO] Started compute_subnet with PID: 16172
2024-12-31 15:02:44,894 [INFO] Started compute_subnet with PID: 16172
2024-12-31 15:02:44,894 [INFO] Started compute_subnet with PID: 16172
2024-12-31 15:02:45,914 [WARNING] Restarting script with administrative privileges...
2024-12-31 15:02:46,122 [INFO] Script relaunched with administrative privileges.
2024-12-31 15:02:46,123 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 15:02:46,679 [INFO] PID file created with PID: 14888
2024-12-31 15:02:46,868 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 15:02:48,823 [INFO] SSH server configured successfully.
2024-12-31 15:02:48,878 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 15:02:58,688 [INFO] Starting ngrok tunnel...
2024-12-31 15:03:07,351 [INFO] Network information synchronized successfully
2024-12-31 15:03:08,529 [INFO] 
==================================================
2024-12-31 15:03:08,530 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 15:03:08,531 [INFO] SSH Command: ssh://HP@4.tcp.eu.ngrok.io:15826
2024-12-31 15:03:08,531 [INFO] Password: banadda
2024-12-31 15:03:08,533 [INFO] ==================================================

2024-12-31 18:03:58,528 [ERROR] Failed to stop polaris: (pid=14888)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=14888)
2024-12-31 18:03:58,528 [ERROR] Failed to stop polaris: (pid=14888)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=14888)
2024-12-31 18:03:58,528 [ERROR] Failed to stop polaris: (pid=14888)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=14888)
2024-12-31 18:03:58,590 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:03:58,590 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:03:58,590 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:04:08,041 [INFO] PID file for 'polaris' created with PID: 22672
2024-12-31 18:04:08,041 [INFO] PID file for 'polaris' created with PID: 22672
2024-12-31 18:04:08,041 [INFO] PID file for 'polaris' created with PID: 22672
2024-12-31 18:04:08,041 [INFO] Started polaris with PID: 22672
2024-12-31 18:04:08,041 [INFO] Started polaris with PID: 22672
2024-12-31 18:04:08,041 [INFO] Started polaris with PID: 22672
2024-12-31 18:04:08,056 [INFO] PID file for 'compute_subnet' created with PID: 25764
2024-12-31 18:04:08,056 [INFO] PID file for 'compute_subnet' created with PID: 25764
2024-12-31 18:04:08,056 [INFO] PID file for 'compute_subnet' created with PID: 25764
2024-12-31 18:04:08,057 [INFO] Started compute_subnet with PID: 25764
2024-12-31 18:04:08,057 [INFO] Started compute_subnet with PID: 25764
2024-12-31 18:04:08,057 [INFO] Started compute_subnet with PID: 25764
2024-12-31 18:04:09,260 [WARNING] Restarting script with administrative privileges...
2024-12-31 18:04:09,555 [INFO] Script relaunched with administrative privileges.
2024-12-31 18:04:09,555 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 18:04:10,178 [INFO] PID file created with PID: 8448
2024-12-31 18:04:10,523 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 18:04:22,141 [INFO] SSH server configured successfully.
2024-12-31 18:04:22,213 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 18:04:39,432 [INFO] Starting ngrok tunnel...
2024-12-31 18:04:49,050 [WARNING] Failed to synchronize network information
2024-12-31 18:04:49,051 [INFO] 
==================================================
2024-12-31 18:04:49,051 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 18:04:49,058 [INFO] SSH Command: ssh://HP@0.tcp.in.ngrok.io:13045
2024-12-31 18:04:49,058 [INFO] Password: banadda
2024-12-31 18:04:49,058 [INFO] ==================================================

2024-12-31 18:05:59,727 [ERROR] Failed to stop polaris: (pid=8448)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=8448)
2024-12-31 18:05:59,727 [ERROR] Failed to stop polaris: (pid=8448)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=8448)
2024-12-31 18:05:59,727 [ERROR] Failed to stop polaris: (pid=8448)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=8448)
2024-12-31 18:05:59,755 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:05:59,755 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:05:59,755 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:06:02,789 [INFO] PID file for 'polaris' created with PID: 16932
2024-12-31 18:06:02,789 [INFO] PID file for 'polaris' created with PID: 16932
2024-12-31 18:06:02,789 [INFO] PID file for 'polaris' created with PID: 16932
2024-12-31 18:06:02,790 [INFO] Started polaris with PID: 16932
2024-12-31 18:06:02,790 [INFO] Started polaris with PID: 16932
2024-12-31 18:06:02,790 [INFO] Started polaris with PID: 16932
2024-12-31 18:06:02,806 [INFO] PID file for 'compute_subnet' created with PID: 6080
2024-12-31 18:06:02,806 [INFO] PID file for 'compute_subnet' created with PID: 6080
2024-12-31 18:06:02,806 [INFO] PID file for 'compute_subnet' created with PID: 6080
2024-12-31 18:06:02,807 [INFO] Started compute_subnet with PID: 6080
2024-12-31 18:06:02,807 [INFO] Started compute_subnet with PID: 6080
2024-12-31 18:06:02,807 [INFO] Started compute_subnet with PID: 6080
2024-12-31 18:06:03,789 [WARNING] Restarting script with administrative privileges...
2024-12-31 18:06:03,909 [INFO] Script relaunched with administrative privileges.
2024-12-31 18:06:03,909 [INFO] Relaunching Polaris with administrative privileges.
2024-12-31 18:06:04,527 [INFO] PID file created with PID: 12200
2024-12-31 18:06:04,713 [INFO] SSH directory created at C:\ProgramData\ssh using PowerShell
2024-12-31 18:06:06,857 [INFO] SSH server configured successfully.
2024-12-31 18:06:06,927 [INFO] Windows Firewall configured to allow SSH connections on port 22.
2024-12-31 18:06:16,587 [INFO] Starting ngrok tunnel...
2024-12-31 18:06:23,859 [INFO] 
==================================================
2024-12-31 18:06:23,859 [INFO] System information saved to: c:\users\hp\documents\remote_access_tool\system_info.json
2024-12-31 18:06:23,860 [INFO] ==================================================

2024-12-31 18:06:55,868 [INFO] System information loaded successfully.
2024-12-31 18:06:55,868 [INFO] System information loaded successfully.
2024-12-31 18:06:55,868 [INFO] System information loaded successfully.
2024-12-31 18:51:54,150 [ERROR] Failed to stop polaris: (pid=12200)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=12200)
2024-12-31 18:51:54,150 [ERROR] Failed to stop polaris: (pid=12200)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=12200)
2024-12-31 18:51:54,150 [ERROR] Failed to stop polaris: (pid=12200)
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 726, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 948, in wait
    exit_code = cext.proc_wait(self.pid, cext_timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\documents\remote_access_tool\polaris_cli\start.py", line 154, in stop_polaris
    process.wait(timeout=10)
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\__init__.py", line 1355, in wait
    self._exitcode = self._proc.wait(timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\flower-federated-CFzKsM-I\Lib\site-packages\psutil\_pswindows.py", line 728, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: (pid=12200)
2024-12-31 18:51:54,178 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:51:54,178 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
2024-12-31 18:51:54,178 [WARNING] PID file for 'compute_subnet' does not exist. Nothing to remove.
